# Generated by Django 4.0.5 on 2022-06-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseletter',
            name='executor',
            field=models.ManyToManyField(blank=True, default=1, to='letters.executor', verbose_name='Подписано/Исполнитель'),
        ),
    ]
