# Generated by Django 4.0.5 on 2022-06-28 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_outgoingtype_alter_outecoletter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseletter',
            name='out_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='letters.outgoingtype'),
        ),
    ]
