# Generated by Django 4.0.5 on 2022-06-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_alter_baseletter_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseletter',
            name='way_of_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='letters.wayofdelivery', verbose_name='Способ отправки'),
        ),
    ]
