# Generated by Django 4.0.5 on 2022-06-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_alter_baseletter_way_of_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseletter',
            name='cipher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор темы'),
        ),
    ]
