# Generated by Django 4.0.5 on 2022-06-05 00:31

from django.db import migrations, models
import django.db.models.deletion
import letters.models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0006_alter_baseletter_subj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to=letters.models.get_upload_path, verbose_name='Файл приложения')),
                ('attached_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='letters.baseletter', verbose_name='Письмо, к которому относится данное приложение')),
            ],
        ),
    ]
